spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.wfc.shop.entity